# Generated by Django 3.1.4 on 2021-08-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datePosted',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='validthrough',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
